### PR TITLE
Marked props mentioned in #33 as optional

### LINKED ISSUE #33: IPicker type declarations problem
It seems like there are a few properties (`onColorChange`, `onColorSelected`, `defaultColor`, `color`) declared as required in `IPicker`, although even the example usage snippet shows they are optional and so does runtime. This triggers code assist to treat omitting them as an error.

### PR DESCRIPTION
**Pull request by artus9033**
Fixes #33

### CODE REVIEW

**Comment by artus9033** [comment]
Also re-written the project in TypeScript for code readability and maintainability + added TS buildscripts

**Comment by sodik82** [comment]
wau... need to check it out... not sure how linting will work now.....

**Comment by artus9033** [comment]
Thanks for the notice, I forgot to check for Eslint compatibility; I updated the project to use eslint's monorepo solution for Typescript (https://github.com/typescript-eslint/typescript-eslint), then fixed the code to comply with style rules & pushed it altogether

**Comment by artus9033** [comment]
@sodik82 will you merge now?

**Comment by sodik82** [comment]
thanks for your work. I have take it as basis and released RC versions to see if there are any problems (and there was one). Now it looks stable and I have merged it to the master -> closing this MR now.

**Comment by artus9033** [comment]
Thank you too, happy to have contributed!

**Pull request closed without merging**
